# Software Gardening Almanack - Jupyter Book Configuration
#######################################################################################
# Book settings
title: The Software Gardening Almanack
author: The Software Gardening Community
logo: assets/software-gardening-logo.png

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_multitoc_numbering: true
  home_page_in_navbar: true
  favicon: "favicon.png"

#######################################################################################
# Repository specification settings
repository:
  url: https://github.com/software-gardening/almanack
  path_to_book: "src/book"
  branch: main

#######################################################################################
# Sphinx configuration
sphinx:
  local_extensions:
    gen_check_pages: '_ext'
  extra_extensions:
    # enable sphinx autodoc for package api documentation
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
    - 'gen_check_pages'

  config:
    bibtex_reference_style: super
    # added to help render plotly plots within jupyter-book builds
    # reference: https://github.com/jupyter-book/jupyter-book/issues/2041
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

#######################################################################################
# Bibliography configuration
bibtex_bibfiles:
  - references.bib
