# Software Gardening Almanack - Jupyter Book Configuration
#######################################################################################
# Book settings
title: The Software Gardening Almanack
author: The Software Gardening Community
logo: assets/software-gardening-logo.png

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_multitoc_numbering: true
  home_page_in_navbar: true

#######################################################################################
# Repository specification settings
repository:
  url: https://github.com/software-gardening/almanack
  path_to_book: "src/book"
  branch: main

#######################################################################################
# Sphinx configuration
sphinx:
  config:
    bibtex_reference_style: super

#######################################################################################
# Bibliography configuration
bibtex_bibfiles:
  - references.bib
