# deploys the software gardening almanac content through
# GH Pages using Jupyter Book publishing tools.
---
name: deploy book

on:
  push:
    branches: [main]

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install python env
        uses: ./.github/actions/install-python-env
      - name: Build the jupyter book content
        run: |
          poetry run poe build-book
      - name: Build a PDF from the HTML content
        run: |
          poetry run poe build-book-pdf
      - name: Copy and rename the PDF to the HTML dir
        run: |
          cp src/almanac/_build/pdf/book.pdf \
          src/almanac/_build/html/software-gardening-almanac.pdf
      - name: Deploy book to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/almanac/_build/html
